### ISSUE TITLE
requestVitalPermissions() & showMicrophonePermissionDialog() do not work as coded

### ISSUE THREAD

**Issue by ThomasSunderland** [zelloptt/zello-android-client-sdk#13]
Per the Zello sample app, both of these methods attempt to start a new activity using the application context rather than an activity context (application context is used when calling the configure() method in App.java). Each method attempts to start a new activity using the application context without specifying Intent.FLAG_ACTIVITY_NEW_TASK which results in an exception being thrown and swallowed and the methods silently failing.

The code should probably be updated to include this flag, otherwise neither method will work as intended.

We verified this via two different workarounds: (1) we configured the SDK with an activity context and the methods then worked as expected and (2) we tried running the code within the methods directly from the sample app TalkActivity rather than calling the methods and this also worked fine.

Also, unrelated, but the sample app does not run for me unless I add the menu_set_status resource to the menu.xml file in the v11 directory.

**Comment by adambailey-** [comment]
Do you have any more details on the last line regarding menu_set_status? What do you mean by it "does not run"? It won't compile? It crashes on start?

**Comment by ThomasSunderland** [comment]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

![image](https://cloud.githubusercontent.com/assets/2091370/21859359/452c1ef6-d7fa-11e6-832a-a3e9c30a8312.png)
