### ISSUE TITLE
onMessageStateChanged->MessageIn->Author->DisplayName

### ISSUE THREAD

**Issue by ThomasSunderland** [zelloptt/zello-android-client-sdk#17]
Testing of our integration with PTT v3.54 shows that the onMessageStateChanged callback for incoming activity now shows the Author->DisplayName as the Contact name as opposed to the Contact display name (e.g. "DEVICE_1234" vs. "Thomas"). This was working in PTT v3.25.

Screen shots showing the differences between 3.25 and 3.54. 

**PTT 3.25**
![image](https://cloud.githubusercontent.com/assets/2091370/23710194/d659e352-03e9-11e7-920f-b15c27415d47.png)

**PTT 3.54**
![image](https://cloud.githubusercontent.com/assets/2091370/23710213/ec611742-03e9-11e7-8583-dba8ba6f3f39.png)

**Comment by zello-eugene** [comment]
The 3.57 update should take care of this issue.
