### ISSUE TITLE
Looks like MIGRATION.md misformat

### ISSUE THREAD

**Issue by gelsrc** [zelloptt/zello-android-client-sdk#18]
Looks like MIGRATION.md misformat.
Please see https://github.com/zelloptt/zellowork-windows-client-sdk/issues/1 for explanation.

**Comment by agatx** [comment]
Fixed in bdf1049

**Comment by gelsrc** [comment]
Small note. Mentioned commit bdf1049f4b4c3683d870248c3ce0d97ff2342d66 is unrelated to the fix. Right commit is 8eb77d975fe7577077324e700ad6467c2a195ed6

Have a nice day! :)
