### ISSUE TITLE
zello-sdk-sample-signin not accepting credentials and neither showing error

### ISSUE THREAD

**Issue by shreyaspadhye3011** [zelloptt/zello-android-client-sdk#27]
I checked the demo apps given [here](https://github.com/zelloptt/zello-android-client-sdk#additional-resources) but I'm stuck at the PTT app where it's asking me to run the sign-in app. I tried running the sign-in app but it's not accepting my credentials and neither is it showing any error. Can you help? 

![image](https://user-images.githubusercontent.com/26966103/49683709-fe5a8000-fa7d-11e8-9127-b458acbc0bdb.png)

**Comment by agatx** [comment]
Please post unfiltered output from LogCat

**Comment by shreyaspadhye3011** [comment]
Sure, you can check the logs [here](https://docs.google.com/document/d/1xCgzUghHiFXlxfaz3sN9gRuoyh7_Ya_K2n8OIPnVQbg/edit?usp=sharing)

I had added some loggers to debug and I noticed that `onAppStateChanged` is not getting called which I think should get called after sign in attempt. Am I missing something?

FYI: I'm testing in a simulator. Can that be a problem?

**Comment by agatx** [comment]
Looks like you are missing the main Zello app module on the device
```
2018-12-08 13:34:01.168 1618-4133/? W/ActivityManager: Unable to start service Intent { cmp=com.pttsdk/com.zello.client.ui.Svc } U=0: not found
```
To fix please install `pttsdk.apk` from https://github.com/zelloptt/zello-android-client-sdk/releases

**Comment by shreyaspadhye3011** [comment]
Hi @agatx, That solved it. Thank you so much!

I had one last question - So if I have to use the PTT button in my app, will I need to keep these two extra apps - SignIn & PTT.apk apart from the SDK integration?

Please advise

**Comment by shreyaspadhye3011** [comment]
Thank you @agatx. I'll look into it. Appreciate the help. Closing this issue.
