### ISSUE TITLE
Check which channel I'm in?

### ISSUE THREAD

**Issue by maxkunes** [zelloptt/zello-android-client-sdk#32]
Is there any way to check which channel i'm in. 

My workflow is as follows:

1. Present user with a list of Zello.getInstance().contacts of which they choose one. 
2. At some point, the user will want to transmit, at that point, I need to join them to the channel they selected. What I'm thinking is below.
```
if(Zello.getInstance().currentChannelName != selectedChannelName)
            Zello.getInstance().connectChannel(selectedChannelName) // I'm aware this is async
```

Or... Can I just blindly call connectChannel without issue?

Edit:
It seems I should instead use getSelectedContact and setSelectedContact. Is this correct?

**Comment by agatx** [comment]
Yes, you should use `getSelectedContact` to read currently selected contact/channel and `setSelectedContact` to select a different contact.
