### ISSUE TITLE
Is this SDK can work with Zello Enterprise Server?

### ISSUE THREAD

**Issue by dong-dohai** [zelloptt/zello-android-client-sdk#33]
I am wondering if this SDK is available for Zello Enterprise Server? As I don't see it has a way to specify the server endpoint that I want to connect to.

**Comment by agatx** [comment]
Yes, it works with Zello Enterprise Server, you just supply server address in place of `network` in [signIn](http://zelloptt.github.io/zello-android-client-sdk/zello-sdk-documentation/com/zello/sdk/Zello.html#signIn-java.lang.String-java.lang.String-java.lang.String-boolean-) call.

```java
Zello.getInstance().signIn("zello.mycompany.com", "myuser", "mypassword");
```
