### ISSUE TITLE
Calling any methods within the SDK result in a NPE if configure() was not called first

### ISSUE THREAD

**Issue by ThomasSunderland** [zelloptt/zello-android-client-sdk#9]
The SDK should probably protect against the situation where the client has not called the configure() method, but tries to call other methods. 

Right now calling into any method within the SDK without having first called configure() will result in a NPE occurring because the underlying Sdk reference is null.

We discovered this when running on a device without the PTT app installed. In this scenario we skip calling the configure() method. We were still wired up to handle activity pause/resume though and so we were still calling the Sdk.enterPowerSavingMode()/leavePowerSavingMode() methods. 

We have since added protection on our end so that we do not call these methods if we have not yet called configure(), but I would think that this would be protection offered by the Sdk rather than leaving this to the client. I guess though it could be argued either way.

**Comment by adambailey-** [comment]
Hi Thomas,

Thank you for your feedback. There are a few things to note here.

1. If the PTT app is not installed on a device, there is no reason to ignore calling the Zello.configure() method. If we cannot detect the PTT app from the packageName parameter, any call to the SDK will simply be ignored.
2. We agree that a NPE is an inappropriate way to handle this scenario. However, as listed above, there is no reason for the client to NOT call Zello.configure(). Instead, we will throw a RuntimeException explaining that a call to Zello.configure() is necessary before invoking any method that uses the Sdk instance. This should hopefully mitigate any confusion regarding why the client crashed.

**Comment by ThomasSunderland** [comment]
@adambailey- 

Hi Adam, thank you for your quick response on this issue.

1. This is good to know... we'll make the appropriate changes on our side.

2. I don't really understand the benefit of throwing a RuntimeException rather than a NullPointerException (which is itself a RuntimeException). Both are unchecked and therefore undeclared exceptions and so the client does not know that they need to be handled or could occur. The client app will crash all the same in the described scenario.

**Comment by adambailey-** [comment]
There is of course no benefit in terms of checked vs unchecked Exceptions by throwing a RuntimeException compared to a NullPointerException. The client can still crash from both. The real benefit is in the naming.

Many SDK's have some sort of "configure()" method that is a prerequisite to making other SDK calls. A few examples are the Facebook SDK, Fabric SDK, etc. These both will throw a variation of a RuntimeException if an SDK method is invoked before the prerequisite method is called.

The point here is that the Zello methods should not be invoked unless the prerequisite (Zello.configure()) is met.
