### ISSUE TITLE
cannot access Error :  import com.zello.sdk.Error;

### ISSUE THREAD

**Issue by ashishChaugule** [zelloptt/zello-android-client-sdk#90]
error: cannot access Error
--
 import com.zello.sdk.Error;
bad class file: /codebuild/output/src4269414151/src/...../...../....../libraries/zello-sdk/build/.transforms/c91ec267c7288b25ad652db29b003588/transformed/jetified-zello-sdk-api.jar(/com/zello/sdk/Error.class)
class file has wrong version 61.0, should be 55.0
 Please remove or make s

**Comment by zello-eugene** [comment]
You will need Java 17 support in your project in order to use the library.

**Comment by ashishChaugule** [comment]
Yes, fixed
